import { $redoDescription, $undoDescription } from '../../state/editorStore';

/**
 * The menu tree, as DATA (design: `plans/flexo_v2/design/foundation.md` §3 + §4, Law 4
 * "menus are data"; the tree itself is transcribed from FINAL_DESIGN_INDEX.md's
 * "Consolidated menubar tree", which is authoritative where the two differ).
 *
 * ONE dataset renders three surfaces: the desktop menubar, the `☰` drill-down used by the
 * narrow-desktop collapse and the phone MenuSheet, and (via the command registry) the ⌘K
 * palette. Nothing here knows how any of them look — entries only reference commands by
 * id, and the renderer resolves title / enabled / checked / chord at open time so a menu
 * can never drift from the command or its binding.
 *
 * **Adding an item**: register the command in `src/ui/commands/*.ts` first, then add its
 * entry here, then extend the expected-label list in `menuSpec.test.ts` (which is the
 * transcription guard against the authoritative tree).
 */

export type MenuEntry =
  /** A plain item. `dynamicTitle` overrides `command.title` per open (e.g. "Undo Move"). */
  | { kind: 'command'; commandId: string; dynamicTitle?: () => string }
  /** Same as `command`, but rendered with a ✓ / ◉ glyph driven by `command.checked()`. */
  | { kind: 'checkbox' | 'radio'; commandId: string }
  | { kind: 'submenu'; id: string; label: string; entries: MenuEntry[] }
  /** Rows generated by a registered command provider, re-evaluated on every open. */
  | { kind: 'provider'; providerId: string }
  | { kind: 'separator' };

export interface TopMenu {
  id: string;
  label: string;
  entries: MenuEntry[];
}

const separator: MenuEntry = { kind: 'separator' };

const command = (commandId: string): MenuEntry => ({ kind: 'command', commandId });
const checkbox = (commandId: string): MenuEntry => ({ kind: 'checkbox', commandId });
const radio = (commandId: string): MenuEntry => ({ kind: 'radio', commandId });

/** Collider shapes appear in `COLLIDER_SHAPES` order (Cylinder first — Core's own bias). */
const COLLIDER_SHAPE_IDS = ['Cylinder', 'Box', 'Sphere', 'Capsule'] as const;
const CAMERA_SNAP_DIRS = ['front', 'back', 'left', 'right', 'top', 'bottom'] as const;
const ENVIRONMENT_IDS = [
  'room',
  'kloofendal',
  'evening_road',
  'autumn_field',
  'adams_bridge',
  'aristea_wreck',
  'pretoria_gardens',
  'glasshouse_interior',
  'blue_lagoon_night',
] as const;
const KITTEN_IDS = ['hunter', 'polaris', 'banjo'] as const;
/** `View ▸ Display Filters` order, per design-build-mode.md §5.4. */
const DISPLAY_FILTER_KINDS = [
  'connector',
  'collider',
  'ivaSeat',
  'light',
  'kitten',
  'aid',
] as const;

const FILE_MENU: TopMenu = {
  id: 'file',
  label: 'File',
  entries: [
    command('file.new'),
    command('file.projects'),
    command('file.renameProject'),
    separator,
    command('file.importProject'),
    command('file.exportProject'),
    command('file.shareLink'),
    separator,
    command('file.exportKsa'),
    {
      kind: 'submenu',
      id: 'file.modsFolder',
      label: 'Mods Folder',
      // Status row + the grant actions that currently apply — the submenu's shape follows
      // the File System Access grant state, so it is provider-driven.
      entries: [{ kind: 'provider', providerId: 'modsFolder' }],
    },
  ],
};

const EDIT_MENU: TopMenu = {
  id: 'edit',
  label: 'Edit',
  entries: [
    {
      kind: 'command',
      commandId: 'edit.undo',
      dynamicTitle: () => labelledStep('Undo', $undoDescription.get()),
    },
    {
      kind: 'command',
      commandId: 'edit.redo',
      dynamicTitle: () => labelledStep('Redo', $redoDescription.get()),
    },
    {
      kind: 'submenu',
      id: 'edit.history',
      label: 'History',
      entries: [{ kind: 'provider', providerId: 'history' }],
    },
    separator,
    command('edit.cut'),
    command('edit.copy'),
    command('edit.paste'),
    command('edit.duplicate'),
    command('edit.delete'),
    separator,
    command('chain.begin'),
    command('edit.scaleEverything'),
    separator,
    command('edit.settings'),
  ],
};

const ADD_MENU: TopMenu = {
  id: 'add',
  label: 'Add',
  entries: [
    command('add.subpart'),
    command('add.builtinPart'),
    separator,
    command('add.connector'),
    {
      kind: 'submenu',
      id: 'add.collider',
      label: 'Collider',
      entries: [
        ...COLLIDER_SHAPE_IDS.map((shape) => command(`add.collider:${shape}`)),
        separator,
        {
          kind: 'submenu',
          id: 'add.colliderFit',
          label: 'Fit to Selection',
          entries: COLLIDER_SHAPE_IDS.map((shape) => command(`add.colliderFit:${shape}`)),
        },
      ],
    },
    command('add.ivaSeat'),
    {
      kind: 'submenu',
      id: 'add.light',
      label: 'Light',
      entries: [command('add.light:Spot'), command('add.light:Point')],
    },
    {
      kind: 'submenu',
      id: 'add.kitten',
      label: 'Kitten',
      entries: KITTEN_IDS.map((kind) => command(`add.kitten:${kind}`)),
    },
    separator,
    command('add.primitiveMesh'),
    command('add.importModel'),
    {
      kind: 'submenu',
      id: 'add.customMeshInstances',
      label: 'Custom Mesh Instances',
      // Hidden by the renderer when the provider yields nothing (foundation §3:
      // capability-dependent dynamic items may hide).
      entries: [{ kind: 'provider', providerId: 'customMeshInstances' }],
    },
    command('add.uploadTexture'),
    command('add.newMaterial'),
    separator,
    {
      kind: 'submenu',
      id: 'add.kittenMesh',
      label: 'Make Kitten Mesh',
      entries: KITTEN_IDS.map((kind) => command(`add.kittenMesh:${kind}`)),
    },
    separator,
    command('add.defineEngine'),
  ],
};

const SELECT_MENU: TopMenu = {
  id: 'select',
  label: 'Select',
  entries: [
    command('select.all'),
    command('select.none'),
    command('select.invert'),
    command('select.activeLayer'),
    {
      kind: 'submenu',
      id: 'select.byLayer',
      label: 'By Layer',
      entries: [{ kind: 'provider', providerId: 'layers.select' }],
    },
    separator,
    command('tool.marquee'),
  ],
};

const VIEW_MENU: TopMenu = {
  id: 'view',
  label: 'View',
  entries: [
    command('view.frameSelection'),
    command('view.resetCamera'),
    {
      kind: 'submenu',
      id: 'view.cameraSnap',
      label: 'Camera Snap',
      entries: CAMERA_SNAP_DIRS.map((dir) => command(`view.cameraSnap:${dir}`)),
    },
    separator,
    {
      kind: 'submenu',
      id: 'view.grids',
      label: 'Grids',
      entries: [
        checkbox('view.grid:y'),
        checkbox('view.grid:z'),
        checkbox('view.grid:x'),
        separator,
        command('view.gridSettings'),
      ],
    },
    checkbox('view.hideInterior'),
    {
      kind: 'submenu',
      id: 'view.environment',
      label: 'Environment',
      entries: ENVIRONMENT_IDS.map((preset) => radio(`view.environment:${preset}`)),
    },
    checkbox('view.skyBackground'),
    command('view.sceneLighting'),
    {
      kind: 'submenu',
      id: 'view.lightCoverage',
      label: 'Light Coverage',
      entries: [
        radio('view.lightCoverage:selected'),
        radio('view.lightCoverage:all'),
        radio('view.lightCoverage:off'),
      ],
    },
    checkbox('view.livePreview'),
    separator,
    {
      kind: 'submenu',
      id: 'view.displayFilters',
      label: 'Display Filters',
      entries: DISPLAY_FILTER_KINDS.map((kind) => checkbox(`view.displayFilter:${kind}`)),
    },
    command('view.motionTrails'),
    separator,
    {
      kind: 'submenu',
      id: 'view.measurementOverlays',
      label: 'Measurement Overlays',
      entries: [
        checkbox('view.bbox'),
        radio('view.boundsMode:world'),
        radio('view.boundsMode:oriented'),
        checkbox('view.perMesh'),
        checkbox('view.meshDistance'),
      ],
    },
    {
      kind: 'submenu',
      id: 'view.units',
      label: 'Units',
      entries: [radio('view.unit:m'), radio('view.unit:cm'), radio('view.unit:mm')],
    },
    separator,
    checkbox('view.fpsCounter'),
  ],
};

const TOOLS_MENU: TopMenu = {
  id: 'tools',
  label: 'Tools',
  entries: [
    checkbox('tool.measure'),
    command('tools.addRefLine'),
    {
      kind: 'submenu',
      id: 'tools.addContainer',
      label: 'Add Reference Container',
      entries: [
        command('tools.addContainer:rect'),
        command('tools.addContainer:cylinder'),
        command('tools.addContainer:sphere'),
      ],
    },
    separator,
    command('tools.coverageCheck'),
    {
      kind: 'submenu',
      id: 'tools.sitInSeat',
      label: 'Sit in Seat',
      entries: [{ kind: 'provider', providerId: 'seats' }, separator, command('seat.exit')],
    },
    // ── INTERIM until P5A ──────────────────────────────────────────────────────────
    // Not in the authoritative tree: these two submenus keep the measurement and
    // reference-container LISTS reachable after the v1 Measure popover dies. The
    // Outliner's Aids section replaces them and both providers are deleted then.
    separator,
    {
      kind: 'submenu',
      id: 'tools.measurements',
      label: 'Measurements',
      entries: [{ kind: 'provider', providerId: 'aids.measurements' }],
    },
    {
      kind: 'submenu',
      id: 'tools.containers',
      label: 'Containers',
      entries: [
        { kind: 'provider', providerId: 'aids.containers' },
        separator,
        checkbox('tools.warnPrecision'),
      ],
    },
  ],
};

const WINDOW_MENU: TopMenu = {
  id: 'window',
  label: 'Window',
  entries: [
    checkbox('window.toggleLeft'),
    checkbox('window.toggleRight'),
    checkbox('window.timeline'),
    checkbox('window.toolbar'),
    command('window.resetLayout'),
    separator,
    command('window.assetManager'),
    command('window.notifications'),
  ],
};

const HELP_MENU: TopMenu = {
  id: 'help',
  label: 'Help',
  entries: [
    command('palette.open'),
    command('help.shortcuts'),
    separator,
    command('help.about'),
    command('help.github'),
  ],
};

/** The eight menus, in bar order. Mode switches and the right cluster are not menus. */
export const MENU_SPEC: TopMenu[] = [
  FILE_MENU,
  EDIT_MENU,
  ADD_MENU,
  SELECT_MENU,
  VIEW_MENU,
  TOOLS_MENU,
  WINDOW_MENU,
  HELP_MENU,
];

/** `Undo` with the step label appended when there is one — "Undo Move 3 SubParts". */
function labelledStep(verb: 'Undo' | 'Redo', description: string): string {
  return description ? `${verb} ${description}` : verb;
}
