/**
 * Serializes ICRP's static-object mod XML — the `<Mod>Assets.xml` /
 * `<Mod>GameData.xml` pair mirroring Core's CoreLaunchPad* split
 * (plans/ICRP_PLAN.md P1.04, Appendix A; schema facts F1–F4, F10, F13).
 *
 * Emission style is flexo's: omit-at-identity transforms (with the all-three-axes
 * `<Scale>` invariant), .NET G6 numbers, 4-space pretty print. Element order and
 * the banner comment match KSA's own GlbToXmlUtility output (invariant I8), so a
 * generated file is indistinguishable from a Core one:
 *   MeshAtlas → PbrMaterials → StaticSubObjects → StaticObjects, each object as
 *   SubObjects → Colliders → empty GroundOffset/SurfaceHeight/FootprintRadius.
 */
import { DOMImplementation, XMLSerializer } from '@xmldom/xmldom';
import type { Document as XmlDocument, Element as XmlElement } from '@xmldom/xmldom';
import { buildTransformElement, prettyXml } from '../../../../src/ksa/partXmlSerializer';
import { colliderDimensions } from '../../../../src/ksa/colliderSize';
import { formatG6 } from '../../../../src/ksa/formatG6';
import type { PartCollider, Transform, Vec3 } from './types';

/** The banner KSA's GlbToXmlUtility writes; emitted verbatim (fact F13). */
export const BUNDLER_BANNER = ' This file is autogenerated by GlbToXmlUtility from source assets. ';

/**
 * Core's collider component id on static sub-objects/objects. flexo's vessel
 * exporter uses "flexoColliders" to dodge the feed-container id namespace; static
 * objects have no feeds, so ICRP matches Core exactly.
 */
export const STATIC_COLLIDER_COMPONENT_ID = 'Collider1';

/** One `<PbrMaterial>` declaration (paths mod-relative; Category always Vessel). */
export interface StaticMaterialPlan {
  id: string;
  diffusePath: string;
  normalPath: string;
  aoRoughMetalPath: string;
  /** Optional single-channel blend mask — puts the piece in the Blended bucket (F7). */
  alphaPath?: string;
}

/** One `<StaticSubObject>` to declare. */
export interface StaticPiecePlan {
  id: string;
  /** `<Mesh Id>` — a glTF mesh name (custom atlas node, or a Core mesh id, F12). */
  meshId: string;
  /** `<Material Id>` — a declared or Core `<PbrMaterial>` id. */
  materialId: string;
  /** `<Terrain>true</Terrain>` (F6). */
  terrain?: boolean;
  colliders?: readonly PartCollider[];
}

/** One `<SubObject>` placement row. */
export interface StaticPlacementPlan {
  instanceId: string;
  instanceOf: string;
  transform: Transform;
}

/** One `<StaticObject>` to declare. */
export interface StaticObjectPlan {
  id: string;
  placements: readonly StaticPlacementPlan[];
  colliders?: readonly PartCollider[];
}

/** The GameData metres for one object (null = omit → KSA reads unset). */
export interface StaticGameDataPlan {
  id: string;
  groundOffsetM: number | null;
  surfaceHeightM: number | null;
  footprintRadiusM: number | null;
}

export interface StaticAssetsPlan {
  /** Mod-relative custom mesh-atlas path; omitted when every mesh is a Core reference. */
  meshAtlasPath?: string;
  materials: readonly StaticMaterialPlan[];
  pieces: readonly StaticPiecePlan[];
  objects: readonly StaticObjectPlan[];
}

function el(doc: XmlDocument, name: string, attrs?: Record<string, string>): XmlElement {
  const node = doc.createElement(name);
  if (attrs) for (const [k, v] of Object.entries(attrs)) node.setAttribute(k, v);
  return node;
}

/**
 * `<GroundOffset M="…"/>`-style distance. Always the `M=` attribute — Core's
 * static files write `M=` at every magnitude (`LengthX M="0.8693"`,
 * `GroundOffset M="0.2"`), unlike flexo's vessel builder which switches to `Cm`
 * under 1 m. Byte-faithfulness to Core's bundler output is invariant I8.
 */
function distanceEl(doc: XmlDocument, name: string, meters: number): XmlElement {
  return el(doc, name, { M: formatG6(meters) });
}

function vec3Attrs(doc: XmlDocument, name: string, v: Vec3): XmlElement {
  return el(doc, name, { X: formatG6(v.x), Y: formatG6(v.y), Z: formatG6(v.z) });
}

/**
 * `<Collider Id="Collider1">` with one child element per shape — ICRP's own
 * builder (not flexo's `buildColliderElement`) so distances are always `M=` and
 * the component id is Core's. Every dimension element is emitted unconditionally:
 * `DistanceReference` defaults to NaN, so an omitted `<Radius>`/`<Length*>`
 * would build a NaN Bepu shape in-game.
 */
function buildStaticColliderElement(
  doc: XmlDocument,
  colliders: readonly PartCollider[],
): XmlElement {
  const component = el(doc, 'Collider', { Id: STATIC_COLLIDER_COMPONENT_ID });
  for (const c of colliders) {
    const shape = el(doc, c.shape, { Id: c.id });
    shape.appendChild(vec3Attrs(doc, 'LocationAsmb', c.position));
    shape.appendChild(vec3Attrs(doc, 'Collider2Asmb', c.rotation));
    const dims = colliderDimensions(c.shape, c.scale);
    if (dims.lengthXM != null) shape.appendChild(distanceEl(doc, 'LengthX', dims.lengthXM));
    if (dims.lengthYM != null) shape.appendChild(distanceEl(doc, 'LengthY', dims.lengthYM));
    if (dims.lengthZM != null) shape.appendChild(distanceEl(doc, 'LengthZ', dims.lengthZM));
    if (dims.radiusM != null) shape.appendChild(distanceEl(doc, 'Radius', dims.radiusM));
    component.appendChild(shape);
  }
  return component;
}

/** `<Diffuse Path Category="Vessel"/>`-style texture slot. */
function textureSlot(doc: XmlDocument, name: string, path: string): XmlElement {
  return el(doc, name, { Path: path, Category: 'Vessel' });
}

function buildMaterial(doc: XmlDocument, m: StaticMaterialPlan): XmlElement {
  const mat = el(doc, 'PbrMaterial', { Id: m.id });
  mat.appendChild(textureSlot(doc, 'Diffuse', m.diffusePath));
  mat.appendChild(textureSlot(doc, 'Normal', m.normalPath));
  mat.appendChild(textureSlot(doc, 'AoRoughMetal', m.aoRoughMetalPath));
  if (m.alphaPath) mat.appendChild(textureSlot(doc, 'Alpha', m.alphaPath));
  return mat;
}

function buildPiece(doc: XmlDocument, p: StaticPiecePlan): XmlElement {
  const sub = el(doc, 'StaticSubObject', { Id: p.id });
  const model = el(doc, 'PartModel', { Id: `${p.id}_Model` });
  model.appendChild(el(doc, 'Mesh', { Id: p.meshId }));
  model.appendChild(el(doc, 'Material', { Id: p.materialId }));
  if (p.terrain) {
    const terrain = doc.createElement('Terrain');
    terrain.appendChild(doc.createTextNode('true'));
    model.appendChild(terrain);
  }
  sub.appendChild(model);
  if (p.colliders && p.colliders.length > 0) {
    sub.appendChild(buildStaticColliderElement(doc, p.colliders));
  }
  return sub;
}

function buildObject(doc: XmlDocument, o: StaticObjectPlan): XmlElement {
  const obj = el(doc, 'StaticObject', { Id: o.id });
  for (const p of o.placements) {
    const sub = el(doc, 'SubObject', { Id: p.instanceId, InstanceOf: p.instanceOf });
    const transform = buildTransformElement(doc, p.transform);
    if (transform) sub.appendChild(transform);
    obj.appendChild(sub);
  }
  if (o.colliders && o.colliders.length > 0) {
    obj.appendChild(buildStaticColliderElement(doc, o.colliders));
  }
  // The bundler always emits the three distance elements EMPTY on the asset
  // (all-NaN = unset); the values live in GameData — the Core split (F10/F13).
  obj.appendChild(doc.createElement('GroundOffset'));
  obj.appendChild(doc.createElement('SurfaceHeight'));
  obj.appendChild(doc.createElement('FootprintRadius'));
  return obj;
}

/** Serializes the `<Mod>Assets.xml` document. */
export function serializeStaticAssetsXml(plan: StaticAssetsPlan): string {
  const doc = new DOMImplementation().createDocument(null, 'Assets', null);
  const root = doc.documentElement!;
  doc.insertBefore(doc.createComment(BUNDLER_BANNER), root);
  if (plan.meshAtlasPath) root.appendChild(el(doc, 'MeshAtlas', { Path: plan.meshAtlasPath }));
  for (const m of plan.materials) root.appendChild(buildMaterial(doc, m));
  for (const p of plan.pieces) root.appendChild(buildPiece(doc, p));
  for (const o of plan.objects) root.appendChild(buildObject(doc, o));
  const body = new XMLSerializer().serializeToString(doc);
  return '<?xml version="1.0" encoding="utf-8"?>\n' + prettyXml(body) + '\n';
}

/** Serializes the `<Mod>GameData.xml` document (only the set metres are emitted). */
export function serializeStaticGameDataXml(objects: readonly StaticGameDataPlan[]): string {
  const doc = new DOMImplementation().createDocument(null, 'Assets', null);
  const root = doc.documentElement!;
  for (const o of objects) {
    const gd = el(doc, 'StaticObjectGameData', { Id: o.id });
    if (o.groundOffsetM !== null) gd.appendChild(distanceEl(doc, 'GroundOffset', o.groundOffsetM));
    if (o.surfaceHeightM !== null) {
      gd.appendChild(distanceEl(doc, 'SurfaceHeight', o.surfaceHeightM));
    }
    if (o.footprintRadiusM !== null) {
      gd.appendChild(distanceEl(doc, 'FootprintRadius', o.footprintRadiusM));
    }
    root.appendChild(gd);
  }
  const body = new XMLSerializer().serializeToString(doc);
  return '<?xml version="1.0" encoding="utf-8"?>\n' + prettyXml(body) + '\n';
}
